version: '2'
services:
  jhproject4-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/jhProject4/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jhProject4
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
